name: Deploy to GitHub Pages on Tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./web
      
      - name: Build project
        run: npm run build
        working-directory: ./web

      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './web/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5